version: "3"
services:
  omeka-ecosystem:
    volumes:
      - ../var/files:/srv/omeka/files:Z
  elasticsearch:
    volumes:
      - ../var/es:/usr/share/elasticsearch/data:Z
  mysql:
    volumes:
      - ../var/mysql:/var/lib/mysql:Z
