version: "3"
services:
  omeka-ecosystem:
    container_name: madoc-sbb-standalone-omeka
    build:
      context: ../
    links:
      - mysql
    environment:
      - APP_ENV=${APP_ENV}
      - OMEKA__DATABASE_HOST=madoc-sbb-standalone-database
      - OMEKA__DATABASE_NAME=${MYSQL_DATABASE}
      - OMEKA__DATABASE_USER=${MYSQL_USER}
      - OMEKA__DATABASE_PASSWORD=${MYSQL_PASSWORD}
      - OMEKA__DATABASE_PORT=${MYSQL_PORT}
      - OMEKA__MAIN_SITE_DOMAIN=${MAIN_SITE_DOMAIN}
      - OMEKA__ELUCIDATE_URL=${ELUCIDATE_URL}
      - OMEKA__ELUCIDATE_PUBLIC_DOMAIN=${ELUCIDATE_PUBLIC_DOMAIN}
      - HTTP_PROXY=${HTTP_PROXY}
      - HTTPS_PROXY=${HTTPS_PROXY}
      - HTTP_PROXY_PORT=${HTTP_PROXY_PORT}
      # 1.2.x additions.
      - OMEKA__INTERNAL_URL=${OMEKA_INTERNAL_URL}
      - OMEKA__ANNOTATION_INDEXER=${ANNOTATION_INDEXER}
      - OMEKA__SEARCH_ELASTICSEARCH=madoc-sbb-elasticsearch:9200
      - OMEKA__ANNOTATION_ES_INDEX=${FOUNDA_ANNOTATION_INDEX:-jane-annotations}
      - OMEKA__SEARCH_INDEXER=madoc-sbb-search-indexer:8000
    ports:
      - "8898:80"
    volumes:
      - /private/var/files:/srv/omeka/files:Z

  mysql:
    container_name: madoc-sbb-standalone-database
    build:
      context: ../
      dockerfile: Dockerfile.db
    volumes:
      - /private/var/mysql:/var/lib/mysql:Z
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_PORT=${MYSQL_PORT}


  # 1.2.x additions
  elasticsearch:
    container_name: madoc-sbb-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.2
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.type=single-node"
    volumes:
      - /private/var/es:/usr/share/elasticsearch/data:Z
    ports:
      - 9203:9200
      - 9204:9201

  search-founda:
    image: digirati/jane-founda:${FOUNDA_VERSION:-d0e7610dc15073e85fce20ee42215e192b16907b}
    environment:
      - WORKERS=2
      - search_annotation_index=${FOUNDA_ANNOTATION_INDEX:-jane-annotations}
      - search_elasticsearch_base=madoc-sbb-elasticsearch
      - search_elasticsearch_port=9200
      - search_ssl_boolean=${FOUNDA_SEARCH_SSL:-false}
    ports:
      - 8103:8000
    links:
      - elasticsearch

  madoc-indexer:
    container_name: madoc-sbb-search-indexer
    image: digirati/madoc-indexer:${FOUNDA_INDEXER_VERSION:-6d29685681be404861aa745a39ec3b21a5fb13c2}
    environment:
      - WORKERS=2
      - search_annotation_index=${FOUNDA_ANNOTATION_INDEX:-jane-annotations}
      - search_elasticsearch_base=madoc-sbb-elasticsearch
      - search_elasticsearch_port=9200
      - search_ssl_boolean=${FOUNDA_SEARCH_SSL:-false}
    ports:
      - 8104:8000
    links:
      - omeka-ecosystem
      - elasticsearch
      - search-founda
